PermissionCommand: lp user %player% permission set %perm%
Upgrades:
  faction-flight:
    enabled: true
    message: '&dyour faction has now level &7%upgrade% &dof flight upgrade!'
    levels:
      '1':
        cost: 10000
        value: 1
  faction-warps:
    enabled: true
    levels:
      '1':
        cost: 10000
        value: 2
      '2':
        cost: 20000
        value: 4
      '3':
        cost: 30000
        value: 6
      '0':
        value: 1
    message: '&dyour faction has now level &7%upgrade% &dof fwarps upgrade!'
  faction-powerboost:
    enabled: true
    levels:
      '1':
        cost: 10000
        value: 10
      '2':
        cost: 20000
        value: 20
      '3':
        cost: 30000
        value: 40
    message: '&dyour faction has now level &7%upgrade% &dof faction-powerboost upgrade!'
  mob-xp:
    enabled: true
    levels:
      '1':
        cost: 10000
        value: 2
      '2':
        cost: 20000
        value: 3
      '3':
        cost: 30000
        value: 4
    message: '&dyour faction has now level &7%upgrade% &dof mobs-xp upgrade!'

inv:
  name: '&5Faction Upgrades'
  rows: 2
  items:
    '0':
      upgrade: faction-flight
      type: FEATHER
      damage: 0
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '&aFaction Flight Upgrade'
        lore:
        - '&7Current Level: %current_level%'
        - '&6Max Level: %max_level%'
        - '&7Cost: %cost%'
        - '&6Upgrade Value: %upgrade_value%'
    '1':
      upgrade: faction-warps
      type: ENDER_PEARL
      damage: 0
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '&aFaction Warps Upgrade'
        lore:
        - '&7Current Level: %current_level%'
        - '&6Max Level: %max_level%'
        - '&7Cost: %cost%'
        - '&6Upgrade Value: %upgrade_value%'
    '2':
      upgrade: faction-powerboost
      type: APPLE
      damage: 0
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '&aFaction PowerBoost Upgrade'
        lore:
        - '&7Current Level: %current_level%'
        - '&6Max Level: %max_level%'
        - '&7Cost: %cost%'
        - '&6Upgrade Value: %upgrade_value%'
    '3':
      upgrade: mob-xp
      type: EXP_BOTTLE
      damage: 0
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '&aFaction Mob-Xp Upgrade'
        lore:
        - '&7Current Level: %current_level%'
        - '&6Max Level: %max_level%'
        - '&7Cost: %cost%'
        - '&6Upgrade Value: %upgrade_value%'
